//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Produkty
{
    public int Id { get; set; }
    public string Tytuł { get; set; }
    public string Autor { get; set; }
    public string Kategoria { get; set; }
    public Nullable<int> Cena { get; set; }
    public string Opis { get; set; }
}
